name: "02 Conditional Steps"

on:
  workflow_dispatch:

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Exit Code 0
        id: successful_step
        run: |
          echo "exit code 0"
          exit 0 #Success (exit code 0)
        shell: bash #exmple of changing shell per script

      - name: Step 2 - Execute if previous Succeeded
        if: ${{ success() }} # if previous step succeeded
        run: |
          echo "Running because the previous step succeeded"
